FROM node:lts-alpine3.16 AS build

RUN mkdir /web-ide
WORKDIR /web-ide

# Only run the install target when the package.json file have changed
COPY package.json .
RUN npm install

COPY . .
RUN npm run build

FROM nginx AS runtime

COPY --chown=node --from=build /web-ide/dist /usr/share/nginx/html
