---
devices:
  samplerate: 44100
  chunksize: 8192
  capture:
    type: CoreAudio
    channels: 2
    device: "Soundflower (2ch)"
    format: FLOAT32LE
  playback:
    type: CoreAudio
    channels: 2
    device: "Built-in Output"
    #format: FLOAT32LE
    format: S16LE

mixers:
  mono:
    channels:
      in: 2
      out: 2
    mapping:
      - dest: 0
        sources:
          - channel: 0
            gain: -6
            inverted: false
          - channel: 1
            gain: -6
            inverted: false
      - dest: 1
        sources:
          - channel: 0
            gain: -6
            inverted: false
          - channel: 1
            gain: -6
            inverted: false

filters:
  LR_highpass:
    type: BiquadCombo
    parameters:
      type: LinkwitzRileyHighpass
      freq: 60
      order: 8
  highshelf_123:
    type: Biquad
    parameters:
      type: Highshelf
      freq: 123
      gain: -12
      slope: 6
  highshelf_5k:
    type: Biquad
    parameters:
      type: Highshelf
      freq: 5000
      gain: 9
      slope: 6
  highshelf_12k:
    type: Biquad
    parameters:
      type: Lowpass
      freq: 14300
      q: 0.707

pipeline:
  - type: Mixer
    name: mono
  - type: Filter
    channel: 0
    names:
      - LR_highpass
  - type: Filter
    channel: 1
    names:
      - LR_highpass
  - type: Filter
    channel: 0
    names:
      - highshelf_123
  - type: Filter
    channel: 1
    names:
      - highshelf_123
  - type: Filter
    channel: 0
    names:
      - highshelf_5k
  - type: Filter
    channel: 1
    names:
      - highshelf_5k
  - type: Filter
    channel: 0
    names:
      - highshelf_12k
  - type: Filter
    channel: 1
    names:
      - highshelf_12k
