---
devices:
  samplerate: 44100
  chunksize: 8192
  capture:
    type: CoreAudio
    channels: 2
    device: "Soundflower (2ch)"
    format: FLOAT32LE
  playback:
    type: CoreAudio
    channels: 2
    device: "Built-in Output"
    #format: FLOAT32LE
    format: S16LE

mixers:
  mono:
    channels:
      in: 2
      out: 2
    mapping:
      - dest: 0
        sources:
          - channel: 0
            gain: -6
            inverted: false
          - channel: 1
            gain: -6
            inverted: false
      - dest: 1
        sources:
          - channel: 0
            gain: -6
            inverted: false
          - channel: 1
            gain: -6
            inverted: false

filters:
  LR_highpass:
    type: BiquadCombo
    parameters:
      type: LinkwitzRileyHighpass
      freq: 65
      order: 8
  highshelf_123:
    type: Biquad
    parameters:
      type: Highshelf
      freq: 80
      gain: -12
      slope: 6
  highshelf_5k:
    type: Biquad
    parameters:
      type: Highshelf
      freq: 6000
      gain: 9
      slope: 6
  highshelf_12k:
    type: Biquad
    parameters:
      type: Lowpass
      freq: 14300
      q: 0.707
  peak_80:
    type: Biquad
    parameters:
      type: Peaking
      freq: 80
      q: 1
      gain: 4
  peak_316:
    type: Biquad
    parameters:
      type: Peaking
      freq: 316
      q: 5
      gain: -12.3
  peak_868:
    type: Biquad
    parameters:
      type: Peaking
      freq: 868
      q: 1.5
      gain: -9
  peak_10500:
    type: Biquad
    parameters:
      type: Peaking
      freq: 10500
      q: 2
      gain: -3
  channel_timing_fix:
    type: Delay
    parameters:
      delay: 0.1
      unit: ms
      subsample: false
  gain_to_normal_level:
    type: Gain
    parameters:
      gain: 3

pipeline:
  - type: Mixer
    name: mono
  - type: Filter
    channel: 0
    names:
      - LR_highpass
      - highshelf_123
      - highshelf_5k
      - highshelf_12k
      - peak_80
      - peak_316
      - peak_868
      - peak_10500
      #- channel_timing_fix
      - gain_to_normal_level
  - type: Filter
    channel: 1
    names:
      - LR_highpass
      - highshelf_123
      - highshelf_5k
      - highshelf_12k
      - peak_80
      - peak_316
      - peak_868
      - peak_10500
      - gain_to_normal_level
