---
devices:
  samplerate: 44100
  chunksize: 8192
  capture:
    type: CoreAudio
    channels: 2
    device: "Soundflower (2ch)"
    format: FLOAT32LE
  playback:
    type: CoreAudio
    channels: 2
    device: "Built-in Output"
    format: FLOAT32LE
    #format: S16LE

mixers:
  mono:
    channels:
      in: 2
      out: 2
    mapping:
      - dest: 0
        sources:
          - channel: 0
            gain: -6
            inverted: false
          - channel: 1
            gain: -6
            inverted: false
      - dest: 1
        sources:
          - channel: 0
            gain: -6
            inverted: false
          - channel: 1
            gain: -6
            inverted: false

filters:
  LR_highpass_60:
    type: BiquadCombo
    parameters:
      type: LinkwitzRileyHighpass
      freq: 50
      order: 8
  LR_lowpass:
    type: BiquadCombo
    parameters:
      type: LinkwitzRileyLowpass
      freq: 3500
      order: 4
  HS_1_negative:
    type: Biquad
    parameters:
      type: Highshelf
      freq: 100
      gain: -10
      slope: 12
  HS_2_positive:
    type: Biquad
    parameters:
      type: Highshelf
      freq: 1800
      gain: 9
      slope: 12
  HS_2_negative:
    type: Biquad
    parameters:
      type: Highshelf
      #freq: 4500
      #gain: -4.5
      freq: 3230
      gain: -6
      slope: 6
  HS_3_negative:
    type: Biquad
    parameters:
      type: Highshelf
      freq: 350
      gain: -1.4
      slope: 6
  peak_1:
    type: Biquad
    parameters:
      type: Peaking
      freq: 78
      gain: 10
      q: 3
  peak_2:
    type: Biquad
    parameters:
      type: Peaking
      freq: 185
      gain: -3.8
      q: 2
  peak_3:
    type: Biquad
    parameters:
      type: Peaking
      freq: 650
      gain: 4
      q: 6
  peak_4:
    type: Biquad
    parameters:
      type: Peaking
      freq: 529
      gain: -3.5
      q: 6
  peak_5:
    type: Biquad
    parameters:
      type: Peaking
      freq: 1415
      gain: -2
      q: 2.5
  peak_6:
    type: Biquad
    parameters:
      type: Peaking
      freq: 60
      gain: 6
      q: 5
  peak_7:
    type: Biquad
    parameters:
      type: Peaking
      freq: 3200
      gain: 3
      q: 5
  peak_8:
    type: Biquad
    parameters:
      type: Peaking
      freq: 6600
      gain: 3
      q: 3

  gain_to_normal_level:
    type: Gain
    parameters:
      gain: -5

pipeline:
  - type: Mixer
    name: mono
  - type: Filter
    channel: 0
    names:
      - LR_highpass_60
      - LR_lowpass
      - HS_1_negative
      - HS_2_positive
      - HS_2_negative
      - HS_3_negative
      - peak_1
      - peak_2
      - peak_3
      - peak_4
      - peak_5
      - peak_6
      - peak_7
      - peak_8
      - gain_to_normal_level

#      - HS_1_negative
#      - HS_2_positive
#      - HS_3_positive
#      - LS_1_positive
#      - peak_1
#      - peak_2
#      - peak_3
#      - peak_4
#      - peak_16k
#      - peak_5

  - type: Filter
    channel: 1
    names:
      - LR_highpass_60
      - HS_1_negative
      - HS_2_positive
      - HS_2_negative
      - HS_3_negative
      - peak_1
      - peak_2
      - peak_3
      - peak_4
      - peak_5
      - peak_6
      - peak_7
      - peak_8
      - gain_to_normal_level

#      - HS_1_negative
#      - HS_2_positive
#      - HS_3_positive
#      - LS_1_positive
#      - peak_1
#      - peak_2
#      - peak_3
#      - peak_4
#      - peak_16k
#      - peak_5
