---
devices:
  #samplerate: 44100
  samplerate: 48000
  chunksize: 8192
  capture:
    type: CoreAudio
    channels: 2
    device: "Soundflower (2ch)"
    format: FLOAT32LE
  playback:
    type: CoreAudio
    channels: 2
    device: "Built-in Output"
    format: FLOAT32LE
    #format: S16LE

mixers:
  mono:
    channels:
      in: 2
      out: 2
    mapping:
      - dest: 0
        sources:
          - channel: 0
            gain: -6
            inverted: false
          - channel: 1
            gain: -6
            inverted: false
      - dest: 1
        sources:
          - channel: 0
            gain: -6
            inverted: false
          - channel: 1
            gain: -6
            inverted: false

filters:
  LR_highpass_60:
    type: BiquadCombo
    parameters:
      type: LinkwitzRileyHighpass
      freq: 50
      order: 8
  HS_1_negative:
    type: Biquad
    parameters:
      type: Highshelf
      freq: 117
      gain: -10
      slope: 6
  HS_2_positive:
    type: Biquad
    parameters:
      type: Highshelf
      freq: 506
      gain: 2.9
      slope: 6
  HS_3_positive:
    type: Biquad
    parameters:
      type: Highshelf
      freq: 2000
      gain: 5
      slope: 12
  LS_1_positive:
    type: Biquad
    parameters:
      type: Lowshelf
      freq: 173
      gain: 2.0
      slope: 6
  peak_1:
    type: Biquad
    parameters:
      type: Peaking
      freq: 675
      gain: 4.5
      q: 3
  peak_2:
    type: Biquad
    parameters:
      type: Peaking
      freq: 78
      gain: 4
      q: 2.4
  peak_3:
    type: Biquad
    parameters:
      type: Peaking
      freq: 96
      gain: 4
      q: 3
  peak_4:
    type: Biquad
    parameters:
      type: Peaking
      freq: 180
      gain: -2.3
      q: 3
  peak_16k:
    type: Biquad
    parameters:
      type: Peaking
      freq: 15000
      gain: -3
      q: 3
  peak_5:
    type: Biquad
    parameters:
      type: Peaking
      freq: 1000
      gain: 1.3
      q: 0.8
  peak_6:
    type: Biquad
    parameters:
      type: Peaking
      freq: 3300
      gain: 3
      q: 3
  gain_to_normal_level:
    type: Gain
    parameters:
      gain: -6

pipeline:
#  - type: Mixer
#    name: mono
  - type: Filter
    channel: 0
    names:
      - LR_highpass_60
      - HS_1_negative
      - HS_2_positive
      - HS_3_positive
      - LS_1_positive
      - peak_1
      - peak_2
      - peak_3
      - peak_4
      - peak_16k
      - peak_5
      - peak_6
      - gain_to_normal_level
  - type: Filter
    channel: 1
    names:
      - LR_highpass_60
      - HS_1_negative
      - HS_2_positive
      - HS_3_positive
      - LS_1_positive
      - peak_1
      - peak_2
      - peak_3
      - peak_4
      - peak_16k
      - peak_5
      - peak_6
      - gain_to_normal_level
