name: Docker Image CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build STROEM 1.0 image
        uses: docker/build-push-action@v2
        with:
          context: ./software
          file: ./software/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/stroem:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/stroem:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/stroem:buildcache,mode=max
      - name: Build web-ide image
        uses: docker/build-push-action@v2
        with:
          context: ./software/euphonium/web-ide
          file: ./software/Dockerfile.web-ide
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/web-ide:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/stroem:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/web-ide:buildcache,mode=max
